g++ ./tests/test1.cpp ./tests/Object.cpp -o ./tests/test1.x
g++ ./tests/test2.cpp ./tests/Object.cpp -o ./tests/test2.x
g++ ./tests/test3.cpp ./tests/Object.cpp -o ./tests/test3.x
g++ ./tests/test4.cpp ./tests/Object.cpp -o ./tests/test4.x
g++ ./tests/test5.cpp ./tests/Object.cpp -o ./tests/test5.x
g++ ./tests/test6.cpp ./tests/Object.cpp -o ./tests/test6.x
g++ ./tests/test7.cpp ./tests/Object.cpp -o ./tests/test7.x
g++ ./tests/test8.cpp ./tests/Object.cpp -o ./tests/test8.x