// Autogenerated Scheme to C++ Code
// File: ./tests/test6.cpp

#include <iostream>
#include "Object.h"
using namespace std;


Object predicates(Object x)
{
Object __RetVal;
if (stringp(x))
{
__RetVal = Object("Is a string");
}else
{
if (nullp(x))
{
__RetVal = Object("Is null");
}else
{
if (symbolp(x))
{
__RetVal = Object("Is a symbol");
}else
{
if (listp(x))
{
__RetVal = Object("Is a list");
}else
{
if (zerop(x))
{
__RetVal = Object("Is zero");
}else
{
if (numberp(x))
{
__RetVal = Object("Is a number");
}else
{
__RetVal = Object("Is a USO");
}
}
}
}
}
}
return __RetVal;
}


int main()
{
Object __RetVal;
cout << predicates(Object(0)) ;
cout << endl;
cout << predicates((Object(5) + Object(6))) ;
cout << endl;
cout << predicates(Object ("hello")) ;
cout << endl;
cout << predicates(Object ("(a b c )")) ;
cout << endl;
cout << predicates(Object ("()")) ;
cout << endl;
cout << predicates(Object("hello world")) ;
cout << endl;
return 0;
}
