// Autogenerated Scheme to C++ Code
// File: ./tests/test7.cpp

#include <iostream>
#include "Object.h"
using namespace std;


Object iftest(Object a, Object b, Object c)
{
Object __RetVal;
if (((a == b && (b == c))
{
__RetVal = Object ("all_the_same");
}
else
{
if (!(((a > b || (b > c))
{
__RetVal = Object ("in_ascending_order");
}
else
{
if (!((a < c))
{
__RetVal = Object ("in_decscending_order");
}
else
{
__RetVal = Object ("three_values_passed");
}
}
}
return __RetVal;
}


int main()
{
Object __RetVal;
cout << iftest(Object (10), Object (15), Object (20)) ;
cout << endl;
cout << iftest(Object (10), Object (10), Object (10)) ;
cout << endl;
cout << iftest(Object (20), Object (15), Object (10)) ;
cout << endl;
cout << iftest(Object (15), Object (10), Object (20)) ;
cout << endl;
return 0;
}
